modLoader = "javafml"
loaderVersion = "[42,)"
license = "LGPLv3"

[[mods]]
modId = "bettergamemenu"
version = "${version}"
displayName = "BetterGameMenu-Reset"
displayURL="https://changeme.dev/" #optional
logoFile="logo.png" #optional
credits="MORIMORI0317" #optional
authors="TexTrue, TexTrueStudio, BocchiKessokuTeam" #optional
description = '''
Better Game Menu fork
'''

[[dependencies.bettergamemenu]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettergamemenu]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettergamemenu]]
modId = "cloth_config"
mandatory = true
versionRange = "[8,)"
ordering = "NONE"
side = "BOTH"
