modLoader = "javafml"
loaderVersion = "[37,)"
license = "LGPLv3"

[[mods]]
modId = "bettergamemenu"
version = "${version}"
displayName = "BetterGameMenu-Reset"
displayURL="https://changeme.dev/" #optional
logoFile="logo.png" #optional
credits="MORIMORI0317" #optional
authors="TexTrue, TexTrueStudio, BocchiKessokuTeam" #optional
description = '''
Better Game Menu fork
'''

[[dependencies.bettergamemenu]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettergamemenu]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"
